<?php

declare(strict_types=1);

namespace longlang\phpkafka\Protocol\ShareGroupHeartbeat;

use longlang\phpkafka\Protocol\AbstractResponse;
use longlang\phpkafka\Protocol\ProtocolField;

class ShareGroupHeartbeatResponse extends AbstractResponse
{
    /**
 * The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
 *
 * @var int
 */
protected $throttleTimeMs = 0;

/**
 * The top-level error code, or 0 if there was no error.
 *
 * @var int
 */
protected $errorCode = 0;

/**
 * The top-level error message, or null if there was no error.
 *
 * @var string|null
 */
protected $errorMessage = null;

/**
 * The member ID is generated by the consumer and provided by the consumer for all requests.
 *
 * @var string|null
 */
protected $memberId = null;

/**
 * The member epoch.
 *
 * @var int
 */
protected $memberEpoch = 0;

/**
 * The heartbeat interval in milliseconds.
 *
 * @var int
 */
protected $heartbeatIntervalMs = 0;

/**
 * null if not provided; the assignment otherwise.
 *
 * @var Assignment|null
 */
protected $assignment = null;



    public function __construct()
{
    if (!isset(self::$maps[self::class])) {
        self::$maps[self::class] = [
            new ProtocolField('throttleTimeMs', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('errorCode', 'int16', false, [0,1], [0,1], [], [], null),
new ProtocolField('errorMessage', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('memberId', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('memberEpoch', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('heartbeatIntervalMs', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('assignment', Assignment::class, false, [0,1], [0,1], [0,1], [], null),

        ];
        self::$taggedFieldses[self::class] = [
            
        ];
    }
}
public function getRequestApiKey(): ?int
{
    return 76;
}

public function getFlexibleVersions(): array
{
    return [0,1];
}


    /**
 * @return int
 */
public function getThrottleTimeMs(): int
{
    return $this->throttleTimeMs;
}

/**
 * @param int $throttleTimeMs
 *
 * @return self
 */
public function setThrottleTimeMs(int $throttleTimeMs): self
{
    $this->throttleTimeMs = $throttleTimeMs;

    return $this;
}
/**
 * @return int
 */
public function getErrorCode(): int
{
    return $this->errorCode;
}

/**
 * @param int $errorCode
 *
 * @return self
 */
public function setErrorCode(int $errorCode): self
{
    $this->errorCode = $errorCode;

    return $this;
}
/**
 * @return string|null
 */
public function getErrorMessage(): ?string
{
    return $this->errorMessage;
}

/**
 * @param string|null $errorMessage
 *
 * @return self
 */
public function setErrorMessage(?string $errorMessage): self
{
    $this->errorMessage = $errorMessage;

    return $this;
}
/**
 * @return string|null
 */
public function getMemberId(): ?string
{
    return $this->memberId;
}

/**
 * @param string|null $memberId
 *
 * @return self
 */
public function setMemberId(?string $memberId): self
{
    $this->memberId = $memberId;

    return $this;
}
/**
 * @return int
 */
public function getMemberEpoch(): int
{
    return $this->memberEpoch;
}

/**
 * @param int $memberEpoch
 *
 * @return self
 */
public function setMemberEpoch(int $memberEpoch): self
{
    $this->memberEpoch = $memberEpoch;

    return $this;
}
/**
 * @return int
 */
public function getHeartbeatIntervalMs(): int
{
    return $this->heartbeatIntervalMs;
}

/**
 * @param int $heartbeatIntervalMs
 *
 * @return self
 */
public function setHeartbeatIntervalMs(int $heartbeatIntervalMs): self
{
    $this->heartbeatIntervalMs = $heartbeatIntervalMs;

    return $this;
}
/**
 * @return Assignment|null
 */
public function getAssignment(): ?Assignment
{
    return $this->assignment;
}

/**
 * @param Assignment|null $assignment
 *
 * @return self
 */
public function setAssignment(?Assignment $assignment): self
{
    $this->assignment = $assignment;

    return $this;
}

}