<?php

declare(strict_types=1);

namespace longlang\phpkafka\Protocol\ShareGroupHeartbeat;

use longlang\phpkafka\Protocol\AbstractRequest;
use longlang\phpkafka\Protocol\ProtocolField;

class ShareGroupHeartbeatRequest extends AbstractRequest
{
    /**
 * The group identifier.
 *
 * @var string
 */
protected $groupId = '';

/**
 * The member id generated by the consumer. The member id must be kept during the entire lifetime of the consumer process.
 *
 * @var string
 */
protected $memberId = '';

/**
 * The current member epoch; 0 to join the group; -1 to leave the group.
 *
 * @var int
 */
protected $memberEpoch = 0;

/**
 * null if not provided or if it didn't change since the last heartbeat; the rack ID of consumer otherwise.
 *
 * @var string|null
 */
protected $rackId = null;

/**
 * null if it didn't change since the last heartbeat; the subscribed topic names otherwise.
 *
 * @var string[]|null
 */
protected $subscribedTopicNames = null;



    public function __construct()
{
    if (!isset(self::$maps[self::class])) {
        self::$maps[self::class] = [
            new ProtocolField('groupId', 'string', false, [0,1], [0,1], [], [], null),
new ProtocolField('memberId', 'string', false, [0,1], [0,1], [], [], null),
new ProtocolField('memberEpoch', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('rackId', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('subscribedTopicNames', 'string', true, [0,1], [0,1], [0,1], [], null),

        ];
        self::$taggedFieldses[self::class] = [
            
        ];
    }
}
public function getRequestApiKey(): ?int
{
    return 76;
}

public function getMaxSupportedVersion(): int
{
    return 1;
}

public function getFlexibleVersions(): array
{
    return [0,1];
}


    /**
 * @return string
 */
public function getGroupId(): string
{
    return $this->groupId;
}

/**
 * @param string $groupId
 *
 * @return self
 */
public function setGroupId(string $groupId): self
{
    $this->groupId = $groupId;

    return $this;
}
/**
 * @return string
 */
public function getMemberId(): string
{
    return $this->memberId;
}

/**
 * @param string $memberId
 *
 * @return self
 */
public function setMemberId(string $memberId): self
{
    $this->memberId = $memberId;

    return $this;
}
/**
 * @return int
 */
public function getMemberEpoch(): int
{
    return $this->memberEpoch;
}

/**
 * @param int $memberEpoch
 *
 * @return self
 */
public function setMemberEpoch(int $memberEpoch): self
{
    $this->memberEpoch = $memberEpoch;

    return $this;
}
/**
 * @return string|null
 */
public function getRackId(): ?string
{
    return $this->rackId;
}

/**
 * @param string|null $rackId
 *
 * @return self
 */
public function setRackId(?string $rackId): self
{
    $this->rackId = $rackId;

    return $this;
}
/**
 * @return string[]|null
 */
public function getSubscribedTopicNames(): ?array
{
    return $this->subscribedTopicNames;
}

/**
 * @param string[]|null $subscribedTopicNames
 *
 * @return self
 */
public function setSubscribedTopicNames(?array $subscribedTopicNames): self
{
    $this->subscribedTopicNames = $subscribedTopicNames;

    return $this;
}

}