<?php

declare(strict_types=1);

namespace longlang\phpkafka\Protocol\StreamsGroupHeartbeat;

use longlang\phpkafka\Protocol\AbstractRequest;
use longlang\phpkafka\Protocol\ProtocolField;

class StreamsGroupHeartbeatRequest extends AbstractRequest
{
    /**
 * The group identifier.
 *
 * @var string
 */
protected $groupId = '';

/**
 * The member ID generated by the streams consumer. The member ID must be kept during the entire lifetime of the streams consumer process.
 *
 * @var string
 */
protected $memberId = '';

/**
 * The current member epoch; 0 to join the group; -1 to leave the group; -2 to indicate that the static member will rejoin.
 *
 * @var int
 */
protected $memberEpoch = 0;

/**
 * The current endpoint epoch of this client, represents the latest endpoint epoch this client received
 *
 * @var int
 */
protected $endpointInformationEpoch = 0;

/**
 * null if not provided or if it didn't change since the last heartbeat; the instance ID for static membership otherwise.
 *
 * @var string|null
 */
protected $instanceId = null;

/**
 * null if not provided or if it didn't change since the last heartbeat; the rack ID of the member otherwise.
 *
 * @var string|null
 */
protected $rackId = null;

/**
 * -1 if it didn't change since the last heartbeat; the maximum time in milliseconds that the coordinator will wait on the member to revoke its tasks otherwise.
 *
 * @var int
 */
protected $rebalanceTimeoutMs = -1;

/**
 * The topology metadata of the streams application. Used to initialize the topology of the group and to check if the topology corresponds to the topology initialized for the group. Only sent when memberEpoch = 0, must be non-empty. Null otherwise.
 *
 * @var Topology|null
 */
protected $topology = null;

/**
 * Currently owned active tasks for this client. Null if unchanged since last heartbeat.
 *
 * @var TaskIds[]|null
 */
protected $activeTasks = null;

/**
 * Currently owned standby tasks for this client. Null if unchanged since last heartbeat.
 *
 * @var TaskIds[]|null
 */
protected $standbyTasks = null;

/**
 * Currently owned warm-up tasks for this client. Null if unchanged since last heartbeat.
 *
 * @var TaskIds[]|null
 */
protected $warmupTasks = null;

/**
 * Identity of the streams instance that may have multiple consumers. Null if unchanged since last heartbeat.
 *
 * @var string|null
 */
protected $processId = null;

/**
 * User-defined endpoint for Interactive Queries. Null if unchanged since last heartbeat, or if not defined on the client.
 *
 * @var Endpoint|null
 */
protected $userEndpoint = null;

/**
 * Used for rack-aware assignment algorithm. Null if unchanged since last heartbeat.
 *
 * @var KeyValue[]|null
 */
protected $clientTags = null;

/**
 * Cumulative changelog offsets for tasks. Only updated when a warm-up task has caught up, and according to the task offset interval. Null if unchanged since last heartbeat.
 *
 * @var TaskOffset[]|null
 */
protected $taskOffsets = null;

/**
 * Cumulative changelog end-offsets for tasks. Only updated when a warm-up task has caught up, and according to the task offset interval. Null if unchanged since last heartbeat.
 *
 * @var TaskOffset[]|null
 */
protected $taskEndOffsets = null;

/**
 * Whether all Streams clients in the group should shut down.
 *
 * @var bool
 */
protected $shutdownApplication = false;



    public function __construct()
{
    if (!isset(self::$maps[self::class])) {
        self::$maps[self::class] = [
            new ProtocolField('groupId', 'string', false, [0,1], [0,1], [], [], null),
new ProtocolField('memberId', 'string', false, [0,1], [0,1], [], [], null),
new ProtocolField('memberEpoch', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('endpointInformationEpoch', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('instanceId', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('rackId', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('rebalanceTimeoutMs', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('topology', Topology::class, false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('activeTasks', TaskIds::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('standbyTasks', TaskIds::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('warmupTasks', TaskIds::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('processId', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('userEndpoint', Endpoint::class, false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('clientTags', KeyValue::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('taskOffsets', TaskOffset::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('taskEndOffsets', TaskOffset::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('shutdownApplication', 'bool', false, [0,1], [0,1], [], [], null),

        ];
        self::$taggedFieldses[self::class] = [
            
        ];
    }
}
public function getRequestApiKey(): ?int
{
    return 88;
}

public function getMaxSupportedVersion(): int
{
    return 1;
}

public function getFlexibleVersions(): array
{
    return [0,1];
}


    /**
 * @return string
 */
public function getGroupId(): string
{
    return $this->groupId;
}

/**
 * @param string $groupId
 *
 * @return self
 */
public function setGroupId(string $groupId): self
{
    $this->groupId = $groupId;

    return $this;
}
/**
 * @return string
 */
public function getMemberId(): string
{
    return $this->memberId;
}

/**
 * @param string $memberId
 *
 * @return self
 */
public function setMemberId(string $memberId): self
{
    $this->memberId = $memberId;

    return $this;
}
/**
 * @return int
 */
public function getMemberEpoch(): int
{
    return $this->memberEpoch;
}

/**
 * @param int $memberEpoch
 *
 * @return self
 */
public function setMemberEpoch(int $memberEpoch): self
{
    $this->memberEpoch = $memberEpoch;

    return $this;
}
/**
 * @return int
 */
public function getEndpointInformationEpoch(): int
{
    return $this->endpointInformationEpoch;
}

/**
 * @param int $endpointInformationEpoch
 *
 * @return self
 */
public function setEndpointInformationEpoch(int $endpointInformationEpoch): self
{
    $this->endpointInformationEpoch = $endpointInformationEpoch;

    return $this;
}
/**
 * @return string|null
 */
public function getInstanceId(): ?string
{
    return $this->instanceId;
}

/**
 * @param string|null $instanceId
 *
 * @return self
 */
public function setInstanceId(?string $instanceId): self
{
    $this->instanceId = $instanceId;

    return $this;
}
/**
 * @return string|null
 */
public function getRackId(): ?string
{
    return $this->rackId;
}

/**
 * @param string|null $rackId
 *
 * @return self
 */
public function setRackId(?string $rackId): self
{
    $this->rackId = $rackId;

    return $this;
}
/**
 * @return int
 */
public function getRebalanceTimeoutMs(): int
{
    return $this->rebalanceTimeoutMs;
}

/**
 * @param int $rebalanceTimeoutMs
 *
 * @return self
 */
public function setRebalanceTimeoutMs(int $rebalanceTimeoutMs): self
{
    $this->rebalanceTimeoutMs = $rebalanceTimeoutMs;

    return $this;
}
/**
 * @return Topology|null
 */
public function getTopology(): ?Topology
{
    return $this->topology;
}

/**
 * @param Topology|null $topology
 *
 * @return self
 */
public function setTopology(?Topology $topology): self
{
    $this->topology = $topology;

    return $this;
}
/**
 * @return TaskIds[]|null
 */
public function getActiveTasks(): ?array
{
    return $this->activeTasks;
}

/**
 * @param TaskIds[]|null $activeTasks
 *
 * @return self
 */
public function setActiveTasks(?array $activeTasks): self
{
    $this->activeTasks = $activeTasks;

    return $this;
}
/**
 * @return TaskIds[]|null
 */
public function getStandbyTasks(): ?array
{
    return $this->standbyTasks;
}

/**
 * @param TaskIds[]|null $standbyTasks
 *
 * @return self
 */
public function setStandbyTasks(?array $standbyTasks): self
{
    $this->standbyTasks = $standbyTasks;

    return $this;
}
/**
 * @return TaskIds[]|null
 */
public function getWarmupTasks(): ?array
{
    return $this->warmupTasks;
}

/**
 * @param TaskIds[]|null $warmupTasks
 *
 * @return self
 */
public function setWarmupTasks(?array $warmupTasks): self
{
    $this->warmupTasks = $warmupTasks;

    return $this;
}
/**
 * @return string|null
 */
public function getProcessId(): ?string
{
    return $this->processId;
}

/**
 * @param string|null $processId
 *
 * @return self
 */
public function setProcessId(?string $processId): self
{
    $this->processId = $processId;

    return $this;
}
/**
 * @return Endpoint|null
 */
public function getUserEndpoint(): ?Endpoint
{
    return $this->userEndpoint;
}

/**
 * @param Endpoint|null $userEndpoint
 *
 * @return self
 */
public function setUserEndpoint(?Endpoint $userEndpoint): self
{
    $this->userEndpoint = $userEndpoint;

    return $this;
}
/**
 * @return KeyValue[]|null
 */
public function getClientTags(): ?array
{
    return $this->clientTags;
}

/**
 * @param KeyValue[]|null $clientTags
 *
 * @return self
 */
public function setClientTags(?array $clientTags): self
{
    $this->clientTags = $clientTags;

    return $this;
}
/**
 * @return TaskOffset[]|null
 */
public function getTaskOffsets(): ?array
{
    return $this->taskOffsets;
}

/**
 * @param TaskOffset[]|null $taskOffsets
 *
 * @return self
 */
public function setTaskOffsets(?array $taskOffsets): self
{
    $this->taskOffsets = $taskOffsets;

    return $this;
}
/**
 * @return TaskOffset[]|null
 */
public function getTaskEndOffsets(): ?array
{
    return $this->taskEndOffsets;
}

/**
 * @param TaskOffset[]|null $taskEndOffsets
 *
 * @return self
 */
public function setTaskEndOffsets(?array $taskEndOffsets): self
{
    $this->taskEndOffsets = $taskEndOffsets;

    return $this;
}
/**
 * @return bool
 */
public function getShutdownApplication(): bool
{
    return $this->shutdownApplication;
}

/**
 * @param bool $shutdownApplication
 *
 * @return self
 */
public function setShutdownApplication(bool $shutdownApplication): self
{
    $this->shutdownApplication = $shutdownApplication;

    return $this;
}

}