<?php

declare(strict_types=1);

namespace longlang\phpkafka\Protocol\StreamsGroupHeartbeat;

use longlang\phpkafka\Protocol\AbstractResponse;
use longlang\phpkafka\Protocol\ProtocolField;

class StreamsGroupHeartbeatResponse extends AbstractResponse
{
    /**
 * The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
 *
 * @var int
 */
protected $throttleTimeMs = 0;

/**
 * The top-level error code, or 0 if there was no error
 *
 * @var int
 */
protected $errorCode = 0;

/**
 * The top-level error message, or null if there was no error.
 *
 * @var string|null
 */
protected $errorMessage = null;

/**
 * The member id is always generated by the streams consumer.
 *
 * @var string
 */
protected $memberId = '';

/**
 * The member epoch.
 *
 * @var int
 */
protected $memberEpoch = 0;

/**
 * The heartbeat interval in milliseconds.
 *
 * @var int
 */
protected $heartbeatIntervalMs = 0;

/**
 * Deprecated. The maximum acceptable lag (number of offsets to catch up) for a client to be considered caught-up enough to receive an active task assignment. Use AcceptableRecoveryLag instead.
 *
 * @var int
 */
protected $acceptableRecoveryLagLegacy = 0;

/**
 * The interval in which the task changelog offsets on a client are updated on the broker. The offsets are sent with the next heartbeat after this time has passed.
 *
 * @var int
 */
protected $taskOffsetIntervalMs = 0;

/**
 * The maximum acceptable lag (number of offsets to catch up) for a client to be considered caught-up enough to receive an active task assignment. A value of -1 indicates the broker does not support this configuration.
 *
 * @var int
 */
protected $acceptableRecoveryLag = -1;

/**
 * Indicate zero or more status for the group.
 *
 * @var Status[]|null
 */
protected $status = null;

/**
 * Assigned active tasks for this client. Null if unchanged since last heartbeat.
 *
 * @var TaskIds[]|null
 */
protected $activeTasks = null;

/**
 * Assigned standby tasks for this client. Null if unchanged since last heartbeat.
 *
 * @var TaskIds[]|null
 */
protected $standbyTasks = null;

/**
 * Assigned warm-up tasks for this client. Null if unchanged since last heartbeat.
 *
 * @var TaskIds[]|null
 */
protected $warmupTasks = null;

/**
 * True if the broker does not have an up-to-date topology description for this group. The client should send the topology description via StreamsGroupTopologyDescriptionUpdate.
 *
 * @var bool
 */
protected $topologyDescriptionRequired = false;

/**
 * The endpoint epoch set in the response
 *
 * @var int
 */
protected $endpointInformationEpoch = 0;

/**
 * Global assignment information used for IQ. Null if unchanged since last heartbeat.
 *
 * @var EndpointToPartitions[]|null
 */
protected $partitionsByUserEndpoint = null;



    public function __construct()
{
    if (!isset(self::$maps[self::class])) {
        self::$maps[self::class] = [
            new ProtocolField('throttleTimeMs', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('errorCode', 'int16', false, [0,1], [0,1], [], [], null),
new ProtocolField('errorMessage', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('memberId', 'string', false, [0,1], [0,1], [], [], null),
new ProtocolField('memberEpoch', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('heartbeatIntervalMs', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('acceptableRecoveryLagLegacy', 'int32', false, [0], [0,1], [], [], null),
new ProtocolField('taskOffsetIntervalMs', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('acceptableRecoveryLag', 'int64', false, [1], [0,1], [], [], null),
new ProtocolField('status', Status::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('activeTasks', TaskIds::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('standbyTasks', TaskIds::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('warmupTasks', TaskIds::class, true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('topologyDescriptionRequired', 'bool', false, [1], [0,1], [], [], null),
new ProtocolField('endpointInformationEpoch', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('partitionsByUserEndpoint', EndpointToPartitions::class, true, [0,1], [0,1], [0,1], [], null),

        ];
        self::$taggedFieldses[self::class] = [
            
        ];
    }
}
public function getRequestApiKey(): ?int
{
    return 88;
}

public function getFlexibleVersions(): array
{
    return [0,1];
}


    /**
 * @return int
 */
public function getThrottleTimeMs(): int
{
    return $this->throttleTimeMs;
}

/**
 * @param int $throttleTimeMs
 *
 * @return self
 */
public function setThrottleTimeMs(int $throttleTimeMs): self
{
    $this->throttleTimeMs = $throttleTimeMs;

    return $this;
}
/**
 * @return int
 */
public function getErrorCode(): int
{
    return $this->errorCode;
}

/**
 * @param int $errorCode
 *
 * @return self
 */
public function setErrorCode(int $errorCode): self
{
    $this->errorCode = $errorCode;

    return $this;
}
/**
 * @return string|null
 */
public function getErrorMessage(): ?string
{
    return $this->errorMessage;
}

/**
 * @param string|null $errorMessage
 *
 * @return self
 */
public function setErrorMessage(?string $errorMessage): self
{
    $this->errorMessage = $errorMessage;

    return $this;
}
/**
 * @return string
 */
public function getMemberId(): string
{
    return $this->memberId;
}

/**
 * @param string $memberId
 *
 * @return self
 */
public function setMemberId(string $memberId): self
{
    $this->memberId = $memberId;

    return $this;
}
/**
 * @return int
 */
public function getMemberEpoch(): int
{
    return $this->memberEpoch;
}

/**
 * @param int $memberEpoch
 *
 * @return self
 */
public function setMemberEpoch(int $memberEpoch): self
{
    $this->memberEpoch = $memberEpoch;

    return $this;
}
/**
 * @return int
 */
public function getHeartbeatIntervalMs(): int
{
    return $this->heartbeatIntervalMs;
}

/**
 * @param int $heartbeatIntervalMs
 *
 * @return self
 */
public function setHeartbeatIntervalMs(int $heartbeatIntervalMs): self
{
    $this->heartbeatIntervalMs = $heartbeatIntervalMs;

    return $this;
}
/**
 * @return int
 */
public function getAcceptableRecoveryLagLegacy(): int
{
    return $this->acceptableRecoveryLagLegacy;
}

/**
 * @param int $acceptableRecoveryLagLegacy
 *
 * @return self
 */
public function setAcceptableRecoveryLagLegacy(int $acceptableRecoveryLagLegacy): self
{
    $this->acceptableRecoveryLagLegacy = $acceptableRecoveryLagLegacy;

    return $this;
}
/**
 * @return int
 */
public function getTaskOffsetIntervalMs(): int
{
    return $this->taskOffsetIntervalMs;
}

/**
 * @param int $taskOffsetIntervalMs
 *
 * @return self
 */
public function setTaskOffsetIntervalMs(int $taskOffsetIntervalMs): self
{
    $this->taskOffsetIntervalMs = $taskOffsetIntervalMs;

    return $this;
}
/**
 * @return int
 */
public function getAcceptableRecoveryLag(): int
{
    return $this->acceptableRecoveryLag;
}

/**
 * @param int $acceptableRecoveryLag
 *
 * @return self
 */
public function setAcceptableRecoveryLag(int $acceptableRecoveryLag): self
{
    $this->acceptableRecoveryLag = $acceptableRecoveryLag;

    return $this;
}
/**
 * @return Status[]|null
 */
public function getStatus(): ?array
{
    return $this->status;
}

/**
 * @param Status[]|null $status
 *
 * @return self
 */
public function setStatus(?array $status): self
{
    $this->status = $status;

    return $this;
}
/**
 * @return TaskIds[]|null
 */
public function getActiveTasks(): ?array
{
    return $this->activeTasks;
}

/**
 * @param TaskIds[]|null $activeTasks
 *
 * @return self
 */
public function setActiveTasks(?array $activeTasks): self
{
    $this->activeTasks = $activeTasks;

    return $this;
}
/**
 * @return TaskIds[]|null
 */
public function getStandbyTasks(): ?array
{
    return $this->standbyTasks;
}

/**
 * @param TaskIds[]|null $standbyTasks
 *
 * @return self
 */
public function setStandbyTasks(?array $standbyTasks): self
{
    $this->standbyTasks = $standbyTasks;

    return $this;
}
/**
 * @return TaskIds[]|null
 */
public function getWarmupTasks(): ?array
{
    return $this->warmupTasks;
}

/**
 * @param TaskIds[]|null $warmupTasks
 *
 * @return self
 */
public function setWarmupTasks(?array $warmupTasks): self
{
    $this->warmupTasks = $warmupTasks;

    return $this;
}
/**
 * @return bool
 */
public function getTopologyDescriptionRequired(): bool
{
    return $this->topologyDescriptionRequired;
}

/**
 * @param bool $topologyDescriptionRequired
 *
 * @return self
 */
public function setTopologyDescriptionRequired(bool $topologyDescriptionRequired): self
{
    $this->topologyDescriptionRequired = $topologyDescriptionRequired;

    return $this;
}
/**
 * @return int
 */
public function getEndpointInformationEpoch(): int
{
    return $this->endpointInformationEpoch;
}

/**
 * @param int $endpointInformationEpoch
 *
 * @return self
 */
public function setEndpointInformationEpoch(int $endpointInformationEpoch): self
{
    $this->endpointInformationEpoch = $endpointInformationEpoch;

    return $this;
}
/**
 * @return EndpointToPartitions[]|null
 */
public function getPartitionsByUserEndpoint(): ?array
{
    return $this->partitionsByUserEndpoint;
}

/**
 * @param EndpointToPartitions[]|null $partitionsByUserEndpoint
 *
 * @return self
 */
public function setPartitionsByUserEndpoint(?array $partitionsByUserEndpoint): self
{
    $this->partitionsByUserEndpoint = $partitionsByUserEndpoint;

    return $this;
}

}