<?php

declare(strict_types=1);

namespace longlang\phpkafka\Protocol\AlterUserScramCredentials;

use longlang\phpkafka\Protocol\AbstractStruct;
use longlang\phpkafka\Protocol\ProtocolField;

class ScramCredentialUpsertion extends AbstractStruct
{
    /**
 * The user name.
 *
 * @var string
 */
protected $name = '';

/**
 * The SCRAM mechanism.
 *
 * @var int
 */
protected $mechanism = 0;

/**
 * The number of iterations.
 *
 * @var int
 */
protected $iterations = 0;

/**
 * A random salt generated by the client.
 *
 * @var string
 */
protected $salt = '';

/**
 * The salted password.
 *
 * @var string
 */
protected $saltedPassword = '';



    public function __construct()
{
    if (!isset(self::$maps[self::class])) {
        self::$maps[self::class] = [
            new ProtocolField('name', 'string', false, [0], [0], [], [], null),
new ProtocolField('mechanism', 'int8', false, [0], [0], [], [], null),
new ProtocolField('iterations', 'int32', false, [0], [0], [], [], null),
new ProtocolField('salt', 'bytes', false, [0], [0], [], [], null),
new ProtocolField('saltedPassword', 'bytes', false, [0], [0], [], [], null),

        ];
        self::$taggedFieldses[self::class] = [
            
        ];
    }
}
public function getFlexibleVersions(): array
{
    return [0];
}


    /**
 * @return string
 */
public function getName(): string
{
    return $this->name;
}

/**
 * @param string $name
 *
 * @return self
 */
public function setName(string $name): self
{
    $this->name = $name;

    return $this;
}
/**
 * @return int
 */
public function getMechanism(): int
{
    return $this->mechanism;
}

/**
 * @param int $mechanism
 *
 * @return self
 */
public function setMechanism(int $mechanism): self
{
    $this->mechanism = $mechanism;

    return $this;
}
/**
 * @return int
 */
public function getIterations(): int
{
    return $this->iterations;
}

/**
 * @param int $iterations
 *
 * @return self
 */
public function setIterations(int $iterations): self
{
    $this->iterations = $iterations;

    return $this;
}
/**
 * @return string
 */
public function getSalt(): string
{
    return $this->salt;
}

/**
 * @param string $salt
 *
 * @return self
 */
public function setSalt(string $salt): self
{
    $this->salt = $salt;

    return $this;
}
/**
 * @return string
 */
public function getSaltedPassword(): string
{
    return $this->saltedPassword;
}

/**
 * @param string $saltedPassword
 *
 * @return self
 */
public function setSaltedPassword(string $saltedPassword): self
{
    $this->saltedPassword = $saltedPassword;

    return $this;
}

}