<?php

declare(strict_types=1);

namespace longlang\phpkafka\Protocol\ConsumerGroupHeartbeat;

use longlang\phpkafka\Protocol\AbstractRequest;
use longlang\phpkafka\Protocol\ProtocolField;

class ConsumerGroupHeartbeatRequest extends AbstractRequest
{
    /**
 * The group identifier.
 *
 * @var string
 */
protected $groupId = '';

/**
 * The member id generated by the consumer. The member id must be kept during the entire lifetime of the consumer process.
 *
 * @var string
 */
protected $memberId = '';

/**
 * The current member epoch; 0 to join the group; -1 to leave the group; -2 to indicate that the static member will rejoin.
 *
 * @var int
 */
protected $memberEpoch = 0;

/**
 * null if not provided or if it didn't change since the last heartbeat; the instance Id otherwise.
 *
 * @var string|null
 */
protected $instanceId = null;

/**
 * null if not provided or if it didn't change since the last heartbeat; the rack ID of consumer otherwise.
 *
 * @var string|null
 */
protected $rackId = null;

/**
 * -1 if it didn't change since the last heartbeat; the maximum time in milliseconds that the coordinator will wait on the member to revoke its partitions otherwise.
 *
 * @var int
 */
protected $rebalanceTimeoutMs = -1;

/**
 * null if it didn't change since the last heartbeat; the subscribed topic names otherwise.
 *
 * @var string[]|null
 */
protected $subscribedTopicNames = null;

/**
 * null if it didn't change since the last heartbeat; the subscribed topic regex otherwise.
 *
 * @var string|null
 */
protected $subscribedTopicRegex = null;

/**
 * null if not used or if it didn't change since the last heartbeat; the server side assignor to use otherwise.
 *
 * @var string|null
 */
protected $serverAssignor = null;

/**
 * null if it didn't change since the last heartbeat; the partitions owned by the member.
 *
 * @var TopicPartitions[]|null
 */
protected $topicPartitions = null;



    public function __construct()
{
    if (!isset(self::$maps[self::class])) {
        self::$maps[self::class] = [
            new ProtocolField('groupId', 'string', false, [0,1], [0,1], [], [], null),
new ProtocolField('memberId', 'string', false, [0,1], [0,1], [], [], null),
new ProtocolField('memberEpoch', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('instanceId', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('rackId', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('rebalanceTimeoutMs', 'int32', false, [0,1], [0,1], [], [], null),
new ProtocolField('subscribedTopicNames', 'string', true, [0,1], [0,1], [0,1], [], null),
new ProtocolField('subscribedTopicRegex', 'string', false, [1], [0,1], [1], [], null),
new ProtocolField('serverAssignor', 'string', false, [0,1], [0,1], [0,1], [], null),
new ProtocolField('topicPartitions', TopicPartitions::class, true, [0,1], [0,1], [0,1], [], null),

        ];
        self::$taggedFieldses[self::class] = [
            
        ];
    }
}
public function getRequestApiKey(): ?int
{
    return 68;
}

public function getMaxSupportedVersion(): int
{
    return 1;
}

public function getFlexibleVersions(): array
{
    return [0,1];
}


    /**
 * @return string
 */
public function getGroupId(): string
{
    return $this->groupId;
}

/**
 * @param string $groupId
 *
 * @return self
 */
public function setGroupId(string $groupId): self
{
    $this->groupId = $groupId;

    return $this;
}
/**
 * @return string
 */
public function getMemberId(): string
{
    return $this->memberId;
}

/**
 * @param string $memberId
 *
 * @return self
 */
public function setMemberId(string $memberId): self
{
    $this->memberId = $memberId;

    return $this;
}
/**
 * @return int
 */
public function getMemberEpoch(): int
{
    return $this->memberEpoch;
}

/**
 * @param int $memberEpoch
 *
 * @return self
 */
public function setMemberEpoch(int $memberEpoch): self
{
    $this->memberEpoch = $memberEpoch;

    return $this;
}
/**
 * @return string|null
 */
public function getInstanceId(): ?string
{
    return $this->instanceId;
}

/**
 * @param string|null $instanceId
 *
 * @return self
 */
public function setInstanceId(?string $instanceId): self
{
    $this->instanceId = $instanceId;

    return $this;
}
/**
 * @return string|null
 */
public function getRackId(): ?string
{
    return $this->rackId;
}

/**
 * @param string|null $rackId
 *
 * @return self
 */
public function setRackId(?string $rackId): self
{
    $this->rackId = $rackId;

    return $this;
}
/**
 * @return int
 */
public function getRebalanceTimeoutMs(): int
{
    return $this->rebalanceTimeoutMs;
}

/**
 * @param int $rebalanceTimeoutMs
 *
 * @return self
 */
public function setRebalanceTimeoutMs(int $rebalanceTimeoutMs): self
{
    $this->rebalanceTimeoutMs = $rebalanceTimeoutMs;

    return $this;
}
/**
 * @return string[]|null
 */
public function getSubscribedTopicNames(): ?array
{
    return $this->subscribedTopicNames;
}

/**
 * @param string[]|null $subscribedTopicNames
 *
 * @return self
 */
public function setSubscribedTopicNames(?array $subscribedTopicNames): self
{
    $this->subscribedTopicNames = $subscribedTopicNames;

    return $this;
}
/**
 * @return string|null
 */
public function getSubscribedTopicRegex(): ?string
{
    return $this->subscribedTopicRegex;
}

/**
 * @param string|null $subscribedTopicRegex
 *
 * @return self
 */
public function setSubscribedTopicRegex(?string $subscribedTopicRegex): self
{
    $this->subscribedTopicRegex = $subscribedTopicRegex;

    return $this;
}
/**
 * @return string|null
 */
public function getServerAssignor(): ?string
{
    return $this->serverAssignor;
}

/**
 * @param string|null $serverAssignor
 *
 * @return self
 */
public function setServerAssignor(?string $serverAssignor): self
{
    $this->serverAssignor = $serverAssignor;

    return $this;
}
/**
 * @return TopicPartitions[]|null
 */
public function getTopicPartitions(): ?array
{
    return $this->topicPartitions;
}

/**
 * @param TopicPartitions[]|null $topicPartitions
 *
 * @return self
 */
public function setTopicPartitions(?array $topicPartitions): self
{
    $this->topicPartitions = $topicPartitions;

    return $this;
}

}